import React from "react";


export default function Page() {
  return (
    <>
    <title>Pog Website</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta
      name="description"
      content="Generated by create next app and Made with Elif and Esma"
    />
  </>
  );
}