import Wrapper from '../containers/wrapper';
import { fetchEvents } from '@/features/notion/fetchEvents';

export const metadata = {
  title: 'Pog Website',
  description: 'Generated by create next app and Made with Elif and Esma',
};

export default async function Page() {
    const eventsData = await fetchEvents();

    return (
        <>
            <Wrapper events={eventsData} />
        </>
    );
}